server:
  port: 8777
spring:
  datasource:
    url: jdbc:mysql://192.168.0.212:3306/jdzhzq?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: gxrwk
    password: gxrwk
mybatis-plus:
  mapper-locations: classpath*:org/jeecg/meeting/**/xml/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
swagger:
  enabled: true
  termsOfServiceUrl: 127.0.0.1:9910/gklw
  authorName: tlgklw
  authorEmail:
  authorUrl: 127.0.0.1:9910/gklw/doc.html
  version: 1.0.1
  webBasePackage: org.jeecg
  apiBasePackage: org.jeecg.meeting